### ISSUE TITLE
LaTeX source comments

### ISSUE THREAD

**Issue by wilx** [ThePhD/lepix#10]
According to [some](http://tex.stackexchange.com/questions/13067/utf8x-vs-utf8-inputenc), use of `utf8x` and `ucs` is to be avoided. Adding `\usepackage{microtype}` is always a good idea.

If you want to hide the ugly boxes around links then use `\usepackage[unicode,hidelinks]{hyperref}`. If you do not want to see `\url{}` typeset in monospace font then add `\urlstyle{same}` after it.

You will probably want to start your https://github.com/ThePhD/lepix/blob/master/specification/cited.tex with something like this to get the bibliography into contents table: 

``` latex
\clearpage\phantomsection\addcontentsline{toc}{chapter}{Bibliography}
```

Same file, it might be a good idea to wrap all the URLs in there with `\url{}`.

In https://github.com/ThePhD/lepix/blob/master/specification/lepix-lang.tex, move `\newcommand{\lepix}{LéPiX}` into preamble. Also, there is a warning during LaTeX compilation. This can be solved by turning off page numbering for the title page (see also [hyperref - pdfTeX warning (ext4): destination with the same identifier (name{page.1}) has been already used, duplicate ignored](http://tex.stackexchange.com/questions/18924/pdftex-warning-ext4-destination-with-the-same-identifier-nam-epage-1-has)):

``` latex
\pagenumbering{Alph}
\begin{titlepage}
  \renewcommand{\arraystretch}{1.1}
  \maketitle
  \thispagestyle{empty}
\end{titlepage}
\pagenumbering{arabic}
```

**Comment by ThePhD** [comment]
Thanks for taking the time to read through the specification and give me those LaTeX pointers.

I added everything you said and took all of your suggestions, and even added a few packages to make specifying EBNF grammar stuff a lot easier. I think this'll get us a long way there. I appreciate you taking your time out to do that! Hopefully our language will become more and more badass for it.
