### ISSUE TITLE
Language Reference Manual

### ISSUE THREAD

**Issue by gabriellet** [ThePhD/lepix#13]
We need a language reference manual (in the style of K&R "The C Programming Language"). Due October 26.

**Comment by ThePhD** [comment]
Uh. Is this different from #1 ? I know it says "Specification" instead of "Manual"...

**Comment by gabriellet** [comment]
Oh. I thought that #1 was actually for that first proposal we handed in. My bad.

**Comment by ThePhD** [comment]
http://eel.is/c++draft/

An example of a specification (of the entire C++ draft). It's a bit heavy-handed, but the early parts have a lot of good stuff about EBNF's for various kinds of literals and disambiguation rules. Some of this stuff you can get from the C Reference Manual too, which is [here](https://www.bell-labs.com/usr/dmr/www/cman.pdf).

**Comment by gabriellet** [comment]
Cool I'll close this since its a duplicate.
