### ISSUE TITLE
Hello World Program

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/lepix#5]
Due: **November 19th**

In order to make the Hello World program, we need to have #1, #2, #3, and #4 all completed (to some degree of 'complete'). The program for Hello World will be placed in this issue, and this will be our target for compilation. Things we are probably going to need to be able to understand:
- [ ] Creation of an image type (is image() a 'constructor' of sorts? Perhaps we can just have image 
- [ ] Arrays, arrays initialization
- [ ] for loops
- [ ] `lib.save` function to save an image out

**Comment by ThePhD** [comment]
```
function image hello_world() {
    // How do we want array initialization to feel?
    int8[][] hello_data = {{
  |   | ||| |   |   |||   |   | ||| ||| |   || 
  |   | |   |   |   | |   |   | | | | | |   | |
  ||||| ||  |   |   | |   | | | | | ||  |   | |
  |   | |   |   |   | |   || || | | | | |   | |
  |   | ||| ||| ||| |||   |   | ||| | | ||| || 
}};
    image img( hello_data.width, hello_data.height ); 
    for (int y = 0; y < hello_data.height; ++y) {
        for (int x = 0; x < hello_data.width; ++x) {
            // img[x, y] instead for our language ??
            if (hello_data[y][x] != ' ') {
                img[y][x] = pixel(1, 1, 1);
            }
            else {
                img[y][x] = pixel(0, 0, 0);
            }
        }
    }

    return img;
}

function int main () {
    image img = hello_world();
    lib.save("bark.png", img);
    return 0;
}
```

**Comment by ThePhD** [comment]
- Array access: `arr[ x, y ]` ?
- Better than array access: an index type that can contain 1, 2, 3, ..., n indices in it, accessed by [0][1], along with colloquial terms idx.x, idx.y, idx.z, idx.w ...
- Proper bitmap initialization: a different `bitmap` type? Line ending? De-dent lines or preserve them like python?
- constructors (are probably a pain: struct literals instead)

**Comment by gabriellet** [comment]
Array initialization for bitmap type thing:

```
// bitmap type thing
bitmap[][] hello_data = {{
|   | ||| |   |   |||   |   | ||| ||| |   ||  ,
|   | |   |   |   | |   |   | | | | | |   | | ,
||||| ||  |   |   | |   | | | | | ||  |   | | ,
|   | |   |   |   | |   || || | | | | |   | | ,
|   | ||| ||| ||| |||   |   | ||| | | ||| ||  ,
}};

// versus regular int array
int8[] boop = {1,2,3,4,5};
```

Array resizing??? The compiler should definitely complain if the row sizes don't match. The bitmap thing shouldn't be the same as an int. Size inference and also explicit parameters `bitmap[3][4]` and `bitmap[][] = //stuff` supported.

**Comment by gabriellet** [comment]
```
//swift style declaration?
hello_data: bitmap[][] = {{
//blah blah blah
}};
```

Another idea for how declarations could look

**Comment by fennilin** [comment]
Image wrapping around bitmaps? (i.e. user doesn't have to write the for loop above)

```
// bitmap
bitmap[][] hello_data = {{
|   | ||| |   |   |||   |   | ||| ||| |   ||  ,
|   | |   |   |   | |   |   | | | | | |   | | ,
||||| ||  |   |   | |   | | | | | ||  |   | | ,
|   | |   |   |   | |   || || | | | | |   | | ,
|   | ||| ||| ||| |||   |   | ||| | | ||| ||  ,
}};

// image wrapping
image img(hello_data);
```

**Comment by ThePhD** [comment]
```
let mybitmap : bitmap[][] = [
|   | ||| |   |   |||   |   | ||| ||| |   ||  ;
|   | |   |   |   | |   |   | | | | | |   | | ;
||||| ||  |   |   | |   | | | | | ||  |   | | ;
|   | |   |   |   | |   || || | | | | |   | | ;
|   | ||| ||| ||| |||   |   | ||| | | ||| ||  ;
];
```

let-like syntax vs. the C syntax.

**Comment by ThePhD** [comment]
It's not what we envisioned, but it will work for what we turn in: 
![image](https://cloud.githubusercontent.com/assets/2886436/20463829/edcd5238-af09-11e6-8e3a-6ec581d7924b.png)
