### ISSUE TITLE
Uh. System Architect

### ISSUE THREAD

**Issue by ThePhD** [ThePhD/lepix#9]
So, uh. This is a role that is supposed to be apart of the group. I totally forgot about it when we were initially assigning roles and I don't have anyone pegged for it in the Proposal.

The role's job is basically to choose version control, help set up development environments, and figure out other things related to what is necessary to run / build / develop all the code. Does anyone want to formally put their name on it?

**Comment by gabriellet** [comment]
So when you say necessary to run code does this include figuring out how to talk to the GPU?

**Comment by ThePhD** [comment]
I just mean things like if we need any external libraries present on the computers we run on (certain packages and the like), DLLs, build environment, test environment... Mostly development stuff. Figuring out how to talk to the GPU is going to be the problem of the person who works on the back end and does the code generation there (mainly what I'm figuring out right now).

**Comment by ThePhD** [comment]
I'll take this role.
